### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by licaon-kter** [DavidCecil50/OBDZero#5]
this draft recipe **metadata/dc.local.electriccar.yml**
```
License: Unknown
SourceCode: https://github.com/DavidCecil50/OBDZero
IssueTracker: https://github.com/DavidCecil50/OBDZero/issues

RepoType: git
Repo: https://github.com/DavidCecil50/OBDZero

Builds:
  - versionName: '3.86'
    versionCode: 20
    commit: 5d9a956578fec8f05b78dd199c267431414aca24
    subdir: app
    sudo:
      - echo "deb https://deb.debian.org/debian bullseye main" > /etc/apt/sources.list.d/bullseye.list
      - apt-get update
      - apt-get install -y -t bullseye openjdk-11-jdk-headless
      - update-java-alternatives --set java-1.11.0-openjdk-amd64
    gradle:
      - yes

AutoUpdateMode: None
UpdateCheckMode: Tags
```
builds fine...but... is the repo still alive to add Fastlane (https://gitlab.com/-/snippets/1895688) and all that's needed for an inclusion (https://f-droid.org/en/docs/Inclusion_Policy/) ?
